// <auto-generated />
using System;
using EstacionamientoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstacionamientoAPI.Migrations
{
    [DbContext(typeof(EstacionamientoContext))]
    partial class EstacionamientoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Estancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Placa");

                    b.ToTable("Estancias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoraEntrada = new DateTime(2023, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSalida = new DateTime(2023, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "ABC-12345"
                        },
                        new
                        {
                            Id = 2,
                            HoraEntrada = new DateTime(2023, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSalida = new DateTime(2023, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "DEF-23456"
                        },
                        new
                        {
                            Id = 3,
                            HoraEntrada = new DateTime(2023, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSalida = new DateTime(2023, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "GHI-34567"
                        },
                        new
                        {
                            Id = 4,
                            HoraEntrada = new DateTime(2023, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSalida = new DateTime(2023, 3, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "JKL-45678"
                        },
                        new
                        {
                            Id = 5,
                            HoraEntrada = new DateTime(2023, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraSalida = new DateTime(2023, 3, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Placa = "MNO-56789"
                        });
                });

            modelBuilder.Entity("Vehiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Placa");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Placa = "ABC-12345",
                            Tipo = 0
                        },
                        new
                        {
                            Placa = "DEF-23456",
                            Tipo = 1
                        },
                        new
                        {
                            Placa = "GHI-34567",
                            Tipo = 2
                        },
                        new
                        {
                            Placa = "JKL-45678",
                            Tipo = 1
                        },
                        new
                        {
                            Placa = "MNO-56789",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("Estancia", b =>
                {
                    b.HasOne("Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("Placa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
